"""change_workspace_id_type_to_string

Revision ID: 03e0e63fda91
Revises: 11009c9d502f
Create Date: 2025-12-25 06:20:48.139217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03e0e63fda91'
down_revision: Union[str, None] = '11009c9d502f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'workspace_id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('chats', 'workspace_id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('instructions', 'workspace_id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('wizards', 'workspace_id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('workflows', 'workspace_id',
               existing_type=mysql.CHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'workspace_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('wizards', 'workspace_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('instructions', 'workspace_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('chats', 'workspace_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('chat_history', 'workspace_id',
               existing_type=sa.String(length=255),
               type_=mysql.CHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
