"""remove_function_call_logs_table

Revision ID: 11009c9d502f
Revises: 95836fa7254d
Create Date: 2025-12-24 13:24:17.840245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11009c9d502f'
down_revision: Union[str, None] = '95836fa7254d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_function_call_logs_id'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_session_id'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_timestamp'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_tool'), table_name='function_call_logs')
    op.drop_table('function_call_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_call_logs',
    sa.Column('timestamp', mysql.DATETIME(), nullable=False),
    sa.Column('tool', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('params', mysql.JSON(), nullable=True),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('response', mysql.JSON(), nullable=True),
    sa.Column('error', mysql.TEXT(), nullable=True),
    sa.Column('duration_ms', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tokens_used', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('additional_metadata', mysql.JSON(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('workspace_id', mysql.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_function_call_logs_tool'), 'function_call_logs', ['tool'], unique=False)
    op.create_index(op.f('ix_function_call_logs_timestamp'), 'function_call_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_function_call_logs_session_id'), 'function_call_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_function_call_logs_id'), 'function_call_logs', ['id'], unique=False)
    # ### end Alembic commands ###
