"""add_created_by_column_to_some_tables

Revision ID: 91a8bc6e97bb
Revises: 03e0e63fda91
Create Date: 2025-12-25 06:36:24.201861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a8bc6e97bb'
down_revision: Union[str, None] = '03e0e63fda91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('wizards', sa.Column('created_by', sa.String(length=255), nullable=False))
    op.add_column('workflows', sa.Column('created_by', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'created_by')
    op.drop_column('wizards', 'created_by')
    op.drop_column('instructions', 'created_by')
    # ### end Alembic commands ###
