"""add_workspace_id_to_all_tables

Revision ID: 95836fa7254d
Revises: c316c19f7cad
Create Date: 2025-12-23 13:42:12.772029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95836fa7254d'
down_revision: Union[str, None] = 'c316c19f7cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('chats', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('function_call_logs', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('instructions', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('wizards', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('workflows', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'workspace_id')
    op.drop_column('wizards', 'workspace_id')
    op.drop_column('instructions', 'workspace_id')
    op.drop_column('function_call_logs', 'workspace_id')
    op.drop_column('chats', 'workspace_id')
    op.drop_column('chat_history', 'workspace_id')
    # ### end Alembic commands ###
