"""remove_unique_attribute_for_workflow_name_column

Revision ID: ba4aaad73d54
Revises: 91a8bc6e97bb
Create Date: 2025-12-25 12:00:34.270315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4aaad73d54'
down_revision: Union[str, None] = '91a8bc6e97bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('name'), 'workflows', ['name'], unique=True)
    # ### end Alembic commands ###
