"""drop_agent_type_columns

Revision ID: c316c19f7cad
Revises: e65058a0982e
Create Date: 2025-11-03 05:35:28.317404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c316c19f7cad'
down_revision: Union[str, None] = 'e65058a0982e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'agent_type')
    op.drop_column('workflows', 'agent_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('agent_type', mysql.ENUM('voice_agent', 'text_agent', 'both'), nullable=False))
    op.add_column('instructions', sa.Column('agent_type', mysql.ENUM('voice_agent', 'text_agent', 'both'), nullable=False))
    # ### end Alembic commands ###
