"""empty message

Revision ID: 1f54640e6431
Revises: 72051cc2c81b
Create Date: 2025-10-19 05:53:59.635957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f54640e6431'
down_revision: Union[str, None] = '72051cc2c81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('domain'), table_name='crawled_domains')
    op.drop_index(op.f('ix_crawled_domains_id'), table_name='crawled_domains')
    op.drop_constraint(op.f('documents_ibfk_1'), 'documents', type_='foreignkey')
    op.drop_table('crawled_domains')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(op.f('chats_ibfk_1'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    op.drop_table('users')
    op.drop_index(op.f('ix_crawl_jobs_id'), table_name='crawl_jobs')
    op.drop_index(op.f('job_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_function_call_logs_user_id'), table_name='function_call_logs')
    op.drop_column('function_call_logs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_call_logs', sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('ix_function_call_logs_user_id'), 'function_call_logs', ['user_id'], unique=False)
    op.add_column('chats', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chats_ibfk_1'), 'chats', 'users', ['user_id'], ['id'])
    op.create_table('documents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('html', mysql.LONGTEXT(), nullable=True),
    sa.Column('markdown', mysql.LONGTEXT(), nullable=True),
    sa.Column('ai_markdown', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Indicates the document markdown generated with AI model or is simple text or html text output'),
    sa.Column('uri', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('domain_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('manual', 'crawl'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('agent_type', mysql.ENUM('voice_agent', 'text_agent', 'both'), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'vectorized', 'error'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['crawled_domains.id'], name=op.f('documents_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('init_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('recursive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('save_in_vector', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('logs', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.JSON(), nullable=True),
    sa.Column('started_at', mysql.DATETIME(), nullable=True),
    sa.Column('end_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('job_id'), 'crawl_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_crawl_jobs_id'), 'crawl_jobs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_type', mysql.ENUM('admin', 'supporter', 'customer'), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('email_verified_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('crawled_domains',
    sa.Column('domain', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_crawled_domains_id'), 'crawled_domains', ['id'], unique=False)
    op.create_index(op.f('domain'), 'crawled_domains', ['domain'], unique=True)
    # ### end Alembic commands ###
