"""add_function_call_log_table

Revision ID: aa522221a5d3
Revises: 8776e24d1880
Create Date: 2025-08-18 03:16:15.026836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa522221a5d3'
down_revision: Union[str, None] = '8776e24d1880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function_call_logs',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tool', sa.String(length=255), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_call_logs_id'), 'function_call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_function_call_logs_session_id'), 'function_call_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_function_call_logs_timestamp'), 'function_call_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_function_call_logs_tool'), 'function_call_logs', ['tool'], unique=False)
    op.create_index(op.f('ix_function_call_logs_user_id'), 'function_call_logs', ['user_id'], unique=False)
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_function_call_logs_user_id'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_tool'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_timestamp'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_session_id'), table_name='function_call_logs')
    op.drop_index(op.f('ix_function_call_logs_id'), table_name='function_call_logs')
    op.drop_table('function_call_logs')
    # ### end Alembic commands ###
