version: "3.8"

services:
  # ----------------------- INIT SERVICE ----------------------- #
  init:
    build:
      context: ./idp
      dockerfile: docker/8.4/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=idp-mysql
      - DB_PORT=3307
      - DB_DATABASE=idp_db
      - DB_USERNAME=${IDP_SERVICE_DB_USERNAME:-idp}
      - DB_PASSWORD=${IDP_SERVICE_DB_PASSWORD:-123456789}
      - PASSPORT_PRIVATE_KEY=${PASSPORT_PRIVATE_KEY}
      - PASSPORT_PUBLIC_KEY=${PASSPORT_PUBLIC_KEY}
      - SERVICE_CLIENTS=sina-ai-service,sina-knowledge-service
    volumes:
      - secrets:/secrets
    depends_on:
      idp-mysql:
        condition: service_healthy
    networks:
      - default
    entrypoint: ["/scripts/generate-passport-clients.sh"]



  # ----------------------- IDP MYSQL SERVICE ----------------------- #
  idp-mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "${FORWARD_DB_PORT:-3307}:3307"
    environment:
      MYSQL_ROOT_PASSWORD: "${IDP_SERVICE_DB_PASSWORD:-123456789}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: "3307"
      MYSQL_DATABASE: "idp_db"
      MYSQL_USER: "${IDP_SERVICE_DB_USERNAME:-idp}"
      MYSQL_PASSWORD: "${IDP_SERVICE_DB_PASSWORD:-123456789}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS}"
    volumes:
      - "sail-mysql:/var/lib/mysql"
      - "./idp/docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${IDP_SERVICE_DB_PASSWORD:-123456789}", "-P", "3307"]
      retries: 3
      timeout: 5s



  # ----------------------- IDP SERVICE ----------------------- #
  sina-idp-service:
    build:
      context: ./idp
      dockerfile: docker/8.4/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    container_name: sina-idp-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8000}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER:-0}"
      WWWGROUP: "${WWWGROUP:-0}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      APP_KEY: "${APP_KEY}"
      APP_URL: "http://sina-idp-service"
      APP_DEBUG: true
      APP_MAINTENANCE_DRIVER: file
      DB_CONNECTION: "mysql"
      DB_HOST: "idp-mysql"
      DB_PORT: "3307"
      DB_DATABASE: "idp_db"
      DB_USERNAME: "${IDP_SERVICE_DB_USERNAME:-idp}"
      DB_PASSWORD: "${IDP_SERVICE_DB_PASSWORD:-123456789}"
      SESSION_DRIVER: "database"
      SESSION_LIFETIME: 120
      SESSION_ENCRYPT: false
      SESSION_PATH: /
      SESSION_DOMAIN: null
      LOG_CHANNEL: stack
      LOG_STACK: single
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: database
      SERVICE_CLIENTS: sina-ai-service,sina-knowledge-service
      PASSPORT_PRIVATE_KEY: ${PASSPORT_PRIVATE_KEY}
      PASSPORT_PUBLIC_KEY: ${PASSPORT_PUBLIC_KEY}
    networks:
      - default
    depends_on:
      init:
        condition: service_completed_successfully
      idp-mysql:
        condition: service_healthy



  # ----------------------- AI MYSQL SERVICE ----------------------- #
  ai-mysql:
    image: mysql/mysql-server:8.0
    container_name: ai-mysql
    restart: always
    environment:
      MYSQL_TCP_PORT: "3306"
      MYSQL_PORT: "3306"
      MYSQL_ROOT_PASSWORD: ${AI_SERVICE_DB_PASSWORD}
      MYSQL_DATABASE: aidb
      MYSQL_USER: ${AI_SERVICE_DB_USERNAME}
      MYSQL_PASSWORD: ${AI_SERVICE_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ai-mysql-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${AI_SERVICE_DB_PASSWORD}", "-P", "3306"]
      retries: 3
      timeout: 5s




  # ----------------------- SINA AI SERVICE ----------------------- #
  sina-ai-service:
    build:
      context: ./ai
      dockerfile: dockerfile
    container_name: ai-service
    depends_on:
      init:
        condition: service_completed_successfully
      sina-idp-service:
        condition: service_started
      ai-mysql:
        condition: service_healthy
    environment:
      SERVICE_NAME: sina-ai-service
      MYSQL_HOST: ai-mysql
      MYSQL_USER: ${AI_SERVICE_DB_USERNAME}
      MYSQL_PASSWORD: ${AI_SERVICE_DB_PASSWORD}
      MYSQL_DATABASE: aidb
      MYSQL_PORT: 3306
      REDIS_HOST: ai-redis
      REDIS_PORT: 6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OAUTH_PUBLIC_KEY: ${PASSPORT_PUBLIC_KEY}
      GPT_MODEL: gpt-4.1-mini
      GPT_TITLE_ANALYZER_MODEL: gpt-4.1-mini
      GPT_EMBEDDING_MODEL: text-embedding-3-large
      GPT_RESPONSE_STREAM_SLEEP_SECOND: 0.0001
      CHROMA_PERSIST_DIRECTORY: ./data/chroma
      CHROMA_COLLECTION_NAME: satya_docs
    volumes:
      - secrets:/secrets
    ports:
      - "8090:80"
    networks:
      - default
    command: >
      /bin/sh -c "wait-for-it.sh ai-mysql:3306 -t 120 -- alembic upgrade head &&
                  uvicorn src.api.http.main:app --host=0.0.0.0 --port=80"



  # ----------------------- KNOWLEDGE MYSQL SERVICE ----------------------- #
  knowledge-mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "${FORWARD_DB_PORT:-3308}:3308"
    environment:
      MYSQL_ROOT_PASSWORD: "${KNOWLEDGE_SERVICE_DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: "3308"
      MYSQL_PORT: "3308"
      MYSQL_DATABASE: "knowledge_db"
      MYSQL_USER: "${KNOWLEDGE_SERVICE_DB_USERNAME}"
      MYSQL_PASSWORD: "${KNOWLEDGE_SERVICE_DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS}"
    volumes:
      - knowledge-mysql-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p ${KNOWLEDGE_SERVICE_DB_PASSWORD}", "-P", "3308"]
      retries: 3
      timeout: 5s



  # ----------------------- SINA KNOWLEDGE SERVICE ----------------------- #
  sina-knowledge-service:
    build:
      context: ./knowledge
      dockerfile: dockerfile
    container_name: knowledge-service
    depends_on:
      init:
        condition: service_completed_successfully
      sina-idp-service:
        condition: service_started
      knowledge-mysql:
        condition: service_healthy
    environment:
      SERVICE_NAME: sina-knowledge-service
      DB_HOST: knowledge-mysql
      DB_USER: ${KNOWLEDGE_SERVICE_DB_USERNAME}
      DB_PASS: ${KNOWLEDGE_SERVICE_DB_PASSWORD}
      DB_NAME: knowledge_db
      DB_PORT: 3308
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OAUTH_PUBLIC_KEY: ${PASSPORT_PUBLIC_KEY}
      CHROMA_COLLECTION_NAME: default
      CHROMA_PERSIST_DIRECTORY: "data/chroma"
      OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
    ports:
      - "8050:80"
    networks:
      - default
    volumes:
      - chroma_db:/var/www/html/knowledge/data
      - secrets:/secrets
    command: /bin/sh -c "wait-for-it.sh knowledge-mysql:3308 -t 120 -- alembic upgrade head && uvicorn src.main:app --host=0.0.0.0 --port=80"

volumes:
  sail-mysql:
    driver: local
  ai-mysql-data:
    driver: local
  knowledge-mysql-data:
    driver: local
  chroma_db:
    driver: local
  secrets:
    driver: local

networks:
  default:
    driver: bridge