version: "3.8"

services:
  sina-knowledge-service:
    volumes:
      - ./knowledge:/var/www/html/knowledge/
      - chroma_db:/var/www/html/knowledge/data

  sina-ai-service:
    volumes:
      - ./ai:/var/www/html/ai

  sina-idp-service:
    volumes:
      - "./idp:/var/www/html"
      - "secrets:/secrets"