"""add ai_markdown(boolean) column in documents table.

Revision ID: 1607f16e871c
Revises: 74ab3520936a
Create Date: 2025-06-03 23:53:06.037892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1607f16e871c'
down_revision: Union[str, None] = '74ab3520936a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ai_markdown', sa.Boolean(), nullable=True, comment='Indicates the document markdown generated with AI model or is simple text or html text output'))
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('documents', 'ai_markdown')
    # ### end Alembic commands ###
