"""change workflow.schema column to workflow.flow

Revision ID: 3a00a37fe703
Revises: a5a61722d241
Create Date: 2025-06-08 03:28:30.230935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3a00a37fe703'
down_revision: Union[str, None] = 'a5a61722d241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('workflows', sa.Column('flow', sa.JSON(), nullable=True))
    op.drop_column('workflows', 'schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('schema', mysql.JSON(), nullable=True))
    op.drop_column('workflows', 'flow')
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
