"""add_agent_type_column

Revision ID: 5dfc9dc56212
Revises: 74ca3cb3e674
Create Date: 2025-08-01 22:28:50.822930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dfc9dc56212'
down_revision: Union[str, None] = '74ca3cb3e674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('agent_type', sa.Enum('voice_agent', 'text_agent', 'both', name='agent_type_enum'), nullable=False, default="text_agent"))
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('instructions', sa.Column('agent_type', sa.Enum('voice_agent', 'text_agent', 'both', name='agent_type_enum'), nullable=False, default="text_agent"))
    op.add_column('workflows', sa.Column('agent_type', sa.Enum('voice_agent', 'text_agent', 'both', name='agent_type_enum'), nullable=False, default="text_agent"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'agent_type')
    op.drop_column('instructions', 'agent_type')
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('documents', 'agent_type')
    # ### end Alembic commands ###
