"""Add user_id foreign key to chats table

Revision ID: 74ca3cb3e674
Revises: 8200bc10f8d0
Create Date: 2025-06-28 23:31:41.951987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74ca3cb3e674'
down_revision: Union[str, None] = '8200bc10f8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    # ### end Alembic commands ###
