"""add_ai_bot_model_and_relations

Revision ID: 7a8ed9cbd5db
Revises: bee5b09b86f7
Create Date: 2025-06-30 21:46:40.593031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a8ed9cbd5db'
down_revision: Union[str, None] = 'bee5b09b86f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aibots',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aibots_id'), 'aibots', ['id'], unique=False)
    op.create_index(op.f('ix_aibots_owner_id'), 'aibots', ['owner_id'], unique=False)
    op.create_index(op.f('ix_aibots_workspace_id'), 'aibots', ['workspace_id'], unique=False)
    op.create_table('aibot_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aibot_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('vectorize_id', sa.String(length=255), nullable=True, comment='Vectorized document id in Chroma DB'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aibot_id'], ['aibots.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aibot_id', 'document_id', name='_aibot_document_uc')
    )
    op.create_index(op.f('ix_aibot_documents_id'), 'aibot_documents', ['id'], unique=False)
    op.add_column('chats', sa.Column('aibot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'aibots', ['aibot_id'], ['id'])
    op.alter_column('crawl_jobs', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index(op.f('job_id'), table_name='crawl_jobs')
    op.alter_column('crawled_domains', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index(op.f('domain'), table_name='crawled_domains')
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('instructions', sa.Column('aibot_id', sa.Integer(), nullable=True))
    op.alter_column('instructions', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'instructions', 'aibots', ['aibot_id'], ['id'])
    op.alter_column('wizards', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('workflows', sa.Column('aibot_id', sa.Integer(), nullable=True))
    op.alter_column('workflows', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index(op.f('name'), table_name='workflows')
    op.create_foreign_key(None, 'workflows', 'aibots', ['aibot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_index(op.f('name'), 'workflows', ['name'], unique=True)
    op.alter_column('workflows', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('workflows', 'aibot_id')
    op.alter_column('wizards', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'instructions', type_='foreignkey')
    op.alter_column('instructions', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('instructions', 'aibot_id')
    op.alter_column('documents', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_index(op.f('domain'), 'crawled_domains', ['domain'], unique=True)
    op.alter_column('crawled_domains', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('job_id'), 'crawl_jobs', ['job_id'], unique=True)
    op.alter_column('crawl_jobs', 'workspace_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'aibot_id')
    op.drop_index(op.f('ix_aibot_documents_id'), table_name='aibot_documents')
    op.drop_table('aibot_documents')
    op.drop_index(op.f('ix_aibots_workspace_id'), table_name='aibots')
    op.drop_index(op.f('ix_aibots_owner_id'), table_name='aibots')
    op.drop_index(op.f('ix_aibots_id'), table_name='aibots')
    op.drop_table('aibots')
    # ### end Alembic commands ###
