"""add aibot token

Revision ID: ddf19b5e8c0a
Revises: add_aibot_id_to_wizards
Create Date: 2025-07-10 00:24:37.674877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ddf19b5e8c0a'
down_revision: Union[str, None] = 'add_aibot_id_to_wizards'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aibots', sa.Column('token', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'aibots', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aibots', type_='unique')
    op.drop_column('aibots', 'token')
    # ### end Alembic commands ###
