"""add_phone_to_user

Revision ID: 8a055d9f370d
Revises: 5dfc9dc56212
Create Date: 2025-08-10 01:45:27.774932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8a055d9f370d'
down_revision: Union[str, None] = '5dfc9dc56212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'html',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.alter_column('documents', 'markdown',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.alter_column('documents', 'markdown',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'html',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
