name: Staging Workflow

on:
  push:
    branches:

jobs:
  deploy:
    runs-on: staging-server
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for Docker Compose
        run: |
          echo "Creating temporary .env file..."
          cat <<EOF > .env
APP_KEY=${{ secrets.APP_KEY }}
IDP_SERVICE_DB_USERNAME=${{ secrets.IDP_SERVICE_DB_USERNAME }}
IDP_SERVICE_DB_PASSWORD=${{ secrets.IDP_SERVICE_DB_PASSWORD }}
PASSPORT_PRIVATE_KEY=${{ secrets.PASSPORT_PRIVATE_KEY }}
PASSPORT_PUBLIC_KEY=${{ secrets.PASSPORT_PUBLIC_KEY }}
WWWGROUP=${{ secrets.WWWGROUP }}
WWWUSER=${{ secrets.WWWUSER }}

AI_SERVICE_DB_USERNAME=${{ secrets.AI_SERVICE_DB_USERNAME }}
AI_SERVICE_DB_PASSWORD=${{ secrets.AI_SERVICE_DB_PASSWORD }}

KNOWLEDGE_SERVICE_DB_USERNAME=${{ secrets.KNOWLEDGE_SERVICE_DB_USERNAME }}
KNOWLEDGE_SERVICE_DB_PASSWORD=${{ secrets.KNOWLEDGE_SERVICE_DB_PASSWORD }}

OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
EOF

          # Restrict permissions for security
          chmod 600 .env
          echo ".env file created."

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d --build

      - name: Remove temporary .env file
        if: always()   # ensures cleanup even if previous step fails
        run: |
          echo "Cleaning up .env file..."
          rm -f .env
          echo ".env removed."
