"""remove_unique_constraint_for_workspace_id

Revision ID: 9d6c9faf0aef
Revises: c45eddb709b4
Create Date: 2026-01-08 07:59:52.392646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6c9faf0aef'
down_revision: Union[str, Sequence[str], None] = 'c45eddb709b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=True)
    # ### end Alembic commands ###
